apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-deployment
  namespace: discord-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord
  template:
    metadata:
      labels:
        app: discord
    spec:
      containers:
      - name: discord-bot
        image: hemilabs/discord:latest
        ports:
        - containerPort: 8080
        env:
        - name: WALLET_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: discord-bot-secrets
              key: WALLET_PRIVATE_KEY
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-bot-secrets
              key: BOT_TOKEN
      imagePullSecrets:
      - name: dockerhub-secret

